package com.master.codegenerator.springGenerator;

public interface SpringGeneratorConstantRegex {
    String SPRING_PROJECT_NAME = "#\\{SPRING_PROJECT_NAME\\}#";
    String ALL_SCHEMA_NAME= "#\\{ALL_SCHEMA_NAME\\}#";//all lower letters of database name

    String SCHEMA_PERMISSIONS = "#\\{SCHEMA_PERMISSIONS\\}#";
    String DATABASE_NAME = "#\\{DATABASE_NAME\\}#";
    String FLL_DATABASE_NAME = "#\\{FLL_DATABASE_NAME\\}#";
    String FUL_DATABASE_NAME = "#\\{FUL_DATABASE_NAME\\}#";
    String ALL_DATABASE_NAME = "#\\{ALL_DATABASE_NAME\\}#";
    String TABLE_NAME = "#\\{TABLE_NAME\\}#";
    String ALL_TABLE_NAME = "#\\{ALL_TABLE_NAME\\}#";
    String FLL_TABLE_NAME = "#\\{FLL_TABLE_NAME\\}#";
    String FUL_TABLE_NAME = "#\\{FUL_TABLE_NAME\\}#";
    String AUL_TABLE_NAME = "#\\{AUL_TABLE_NAME\\}#";
    String IMPORT_FOREIGN_REPOSITORIES_AND_MODELS = "#\\{IMPORT_FOREIGN_REPOSITORIES_AND_MODELS\\}#";
    String IMPORT_FOREIGN_MODELS = "#\\{IMPORT_FOREIGN_MODELS\\}#";
    String SERVICE_CREATE_FOREIGN_OBJECTS = "#\\{SERVICE_CREATE_FOREIGN_OBJECTS\\}#";
    String MODEL_ATTRIBUTES = "#\\{MODEL_ATTRIBUTES\\}#";

    String INSTANCE_FOREIGN_REPOSITORIES = "#\\{INSTANCE_FOREIGN_REPOSITORIES\\}#";
    String IMPORT_MODELS_WHICH_REFERENCED_BY_TABLE = "#\\{IMPORT_MODELS_WHICH_REFERENCED_BY_TABLE\\}#";
    String IMPORT_COLUMN_TYPES = "#\\{IMPORT_COLUMN_TYPES\\}#";
    String COLUMNS_TO_ATTRIBUTES = "#\\{COLUMNS_TO_ATTRIBUTES\\}#";
    String FOREIGN_KEYS_TO_ATTRIBUTES = "#\\{FOREIGN_KEYS_TO_ATTRIBUTES\\}#";
    String MODELS_WHICH_REFERENCE_TABLE_TO_ATTRIBUTES = "#\\{MODELS_WHICH_REFERENCE_TABLE_TO_ATTRIBUTES\\}#";
    String MODEL_SETTERS_AND_GETTERS = "#\\{MODEL_SETTERS_AND_GETTERS\\}#";
    String FOREIGN_OBJECTS_SETTERS_AND_GETTERS = "#\\{FOREIGN_OBJECTS_SETTERS_AND_GETTERS\\}#";
    String MODELS_WHICH_REFERENCE_TABLE_SETTERS_AND_GETTERS = "#\\{MODELS_WHICH_REFERENCE_TABLE_SETTERS_AND_GETTERS\\}#";
    String PRIMARY_KEY_SPRING_TYPE = "#\\{PRIMARY_KEY_SPRING_TYPE\\}#";
    String SET_PRIMARY_KEY = "#\\{SET_PRIMARY_KEY\\}#";
    String SERVICE_CONSTRUCTOR_PARAMS = "#\\{SERVICE_CONSTRUCTOR_PARAMS\\}#";
    String SERVICE_CONSTRUCTOR_VALUE_ASSIGMENT = "#\\{SERVICE_CONSTRUCTOR_VALUE_ASSIGMENT\\}#";

    String ADD_AUDIT_CLASS_DECORATOR = "#\\{ADD_AUDIT_CLASS_DECORATOR\\}#";
    String MODEL_AUDIT_ATTRIBUTES = "#\\{MODEL_AUDIT_ATTRIBUTES\\}#";
    String MODEL_AUDIT_SETTERS_AND_GETTERS = "#\\{MODEL_AUDIT_SETTERS_AND_GETTERS\\}#";


}
