package com.master.codegenerator.springGenerator;

public interface SpringGeneratorConstantRegex {
    String DATABASE_NAME = "#\\{DATABASE_NAME\\}#";
    String FLL_DATABASE_NAME = "#\\{FLL_DATABASE_NAME\\}#";
    String FUL_DATABASE_NAME = "#\\{FUL_DATABASE_NAME\\}#";
    String ALL_DATABASE_NAME = "#\\{ALL_DATABASE_NAME\\}#";
    String TABLE_NAME = "#\\{TABLE_NAME\\}#";
    String ALL_TABLE_NAME = "#\\{ALL_TABLE_NAME\\}#";
    String FLL_TABLE_NAME = "#\\{FLL_TABLE_NAME\\}#";
    String FUL_TABLE_NAME = "#\\{FUL_TABLE_NAME\\}#";
    String IMPORT_MODELS_WHICH_REFERENCE_TABLE = "#\\{IMPORT_MODELS_WHICH_REFERENCE_TABLE\\}#";
    String IMPORT_MODELS_WHICH_REFERENCED_BY_TABLE = "#\\{IMPORT_MODELS_WHICH_REFERENCED_BY_TABLE\\}#";
    String IMPORT_COLUMN_TYPES = "#\\{IMPORT_COLUMN_TYPES\\}#";
    String COLUMNS_TO_ATTRIBUTES = "#\\{COLUMNS_TO_ATTRIBUTES\\}#";
    String FOREIGN_KEYS_TO_ATTRIBUTES = "#\\{FOREIGN_KEYS_TO_ATTRIBUTES\\}#";
    String MODELS_WHICH_REFERENCE_TABLE_TO_ATTRIBUTES = "#\\{MODELS_WHICH_REFERENCE_TABLE_TO_ATTRIBUTES\\}#";
    String MODEL_SETTERS_AND_GETTERS = "#\\{MODEL_SETTERS_AND_GETTERS\\}#";
    String FOREIGN_OBJECTS_SETTERS_AND_GETTERS = "#\\{FOREIGN_OBJECTS_SETTERS_AND_GETTERS\\}#";
    String MODELS_WHICH_REFERENCE_TABLE_SETTERS_AND_GETTERS = "#\\{MODELS_WHICH_REFERENCE_TABLE_SETTERS_AND_GETTERS\\}#";
    String PRIMARY_KEY_SPRING_TYPE = "#\\{PRIMARY_KEY_SPRING_TYPE\\}#";
}
