package com.master.codegenerator.reactUtils;

public interface ReactGeneratorConstant {
	String IMPORT_FOREIGN_KEYS_TABLE_NAME = "{IMPORT_FOREIGN_KEYS_TABLE_NAME}";
	String IMPORT_FOREIGN_KEYS_TABLE_NAME_IN_SERVICE = "{IMPORT_FOREIGN_KEYS_TABLE_NAME_IN_SERVICE}";
	String IMPORT_TABLE_SERVICE_FOREIGN_KEYS = "{IMPORT_TABLE_SERVICE_FOREIGN_KEYS}";
	String MAP_COLUMNS_IN_TYPE_FIELDS = "{MAP_COLUMNS_IN_TYPE_FIELDS}";
	String HEADER_OF_INDEX_TABLE = "{HEADER_OF_INDEX_TABLE}";
	String DEFAULT_VALUES_OF_COLUMNS = "{DEFAULT_VALUES_OF_COLUMNS}";
	String NESTED_CATCH_FOREIGN_OBJECTS = "{NESTED_CATCH_FOREIGN_OBJECTS}";
	String INPUT_FIELDS_OF_TABLE = "{INPUT_FIELDS_OF_TABLE}";
	String TABLE_OBJECT_DETAILS_NO_FOREIGN_KEY = "{TABLE_OBJECT_DETAILS_NO_FOREIGN_KEY}";
	String TABLE_OBJECT_DETAILS_FOREIGN_KEY = "{TABLE_OBJECT_DETAILS_FOREIGN_KEY}";
	String TABLES_WHICH_REFERENCE_THIS_TABLE = "{TABLES_WHICH_REFERENCE_THIS_TABLE}";
	String TABLE_COLUMNS_IN_ROW = "{TABLE_COLUMNS_IN_ROW}";
	String IMPORT_INDEX_TABLE_WHICH_REFERENCE_THIS_TABLE = "{IMPORT_INDEX_TABLE_WHICH_REFERENCE_THIS_TABLE}";
	String FORM_OF_FOREIGN_TABLES = "{FORM_OF_FOREIGN_TABLES}";
	String IMPORT_FORM_OF_FOREIGN_TABLES = "{IMPORT_FORM_OF_FOREIGN_TABLES}";
	String ON_SAVE_FOREIGN_OBJECT = "{ON_SAVE_FOREIGN_OBJECT}";
	String ON_CHANGE_FIELD_FOREIGN_OBJECT = "{ON_CHANGE_FIELD_FOREIGN_OBJECT}";
	String GUARDED_ROUTES_OF_TABLES="{GUARDED_ROUTES_OF_TABLES}";
	String IMPORT_COMPONENTS_OF_TABLES="{IMPORT_COMPONENTS_OF_TABLES}";
	String TABLE_FILTER_OPTIONS="{TABLE_FILTER_OPTIONS}";
	String IMPORT_PAGE_OF_FOREIGN_TABLES="{IMPORT_PAGE_OF_FOREIGN_TABLES}";
	String IMPORT_INDEX_TABLE_WHICH_REFECENCE_THIS_TABLE="{IMPORT_INDEX_TABLE_WHICH_REFECENCE_THIS_TABLE}";

	String FL_TABLE_NAME = "{FL_TABLE_NAME}";
	String SFL_TABLE_NAME = "{SFL_TABLE_NAME}";
	String TABLE_SERVICE = "{TABLE_SERVICE}";
	String INDEX_TABLE_NAME = "{INDEX_TABLE_NAME}";
	String ABL_TABLE_NAME = "{ABL_TABLE_NAME}";
	String DEFAULT_TABLE_OBJECT = "{DEFAULT_TABLE_OBJECT}";
	String ASL_TABLE_NAME = "{ASL_TABLE_NAME}";
	String TABLE_FORM = "{TABLE_FORM}";
	String CREATE_TABLE_NAME = "{CREATE_TABLE_NAME}";
	String EDIT_TABLE_NAME = "{EDIT_TABLE_NAME}";
	String PAGE_TABLE_NAME = "{PAGE_TABLE_NAME}";
	String TABLE_EDIT_LINK = "{TABLE_EDIT_LINK}";
	String TABLE_PRIMARY_KEY_COLUMN = "{TABLE_PRIMARY_KEY_COLUMN}";
	String TABLES_ARRAY= "{TABLES_ARRAY}";
}
