package com.master.codegenerator.reactGenerator;

public interface ReactGeneratorConstant {

	String SYSTEM_API_ROUTES = "#{SYSTEM_API_ROUTES}#";
	String REACT_APPLICATION_ROUTES = "#{REACT_APPLICATION_ROUTES}#";
	String APPLICATION_SIDEBAR_ITEMS = "#{APPLICATION_SIDEBAR_ITEMS}#";
	String APPLICATION_PRIVATE_ROUTER_IMPORT = "#{APPLICATION_PRIVATE_ROUTER_IMPORT}#";
	String APPLICATION_PRIVATE_ROUTER_PATH = "#{APPLICATION_PRIVATE_ROUTER_PATH}#";

	String IMPORT_FOREIGN_TABLE_TYPES = "#{IMPORT_FOREIGN_TABLE_TYPES}#";

	String TABLE_ENUM_TYPES = "#{TABLE_ENUM_TYPES}#";

	String TABLE_COLUMNS_CONFIGURATION = "#{TABLE_COLUMNS_CONFIGURATION}#";
	String TABLE_PRIMARY_KEY_COLUMN_TYPE = "#{TABLE_PRIMARY_KEY_COLUMN_TYPE}#";

	String INDEX_OF_TABLES_WHICH_REFERENCE_THIS_TABLE = "#{INDEX_OF_TABLES_WHICH_REFERENCE_THIS_TABLE}#";
	String PAGE_OF_FOREIGN_TABLES = "#{PAGE_OF_FOREIGN_TABLES}#";
	String IMPORT_FOREIGN_TABLE_TYPES_IN_COMPONENT = "#{IMPORT_FOREIGN_TABLE_TYPES_IN_COMPONENT}#";
	String IMPORT_INDEX_OF_FOREIGN_TABLES = "#{IMPORT_INDEX_OF_FOREIGN_TABLES}#";

	String STATE_FOR_MODAL_OF_FOREIGN_TABLES = "#{STATE_FOR_MODAL_OF_FOREIGN_TABLES}#";
	String WATCH_TABLE_FOREIGN_OBJECTS = "#{WATCH_TABLE_FOREIGN_OBJECTS}#";

	String FORM_CHECK_FOREIGN_FIELDS = "#{FORM_CHECK_FOREIGN_FIELDS}#";

	String FORM_FOREIGN_TABLES_FIELDS = "#{FORM_FOREIGN_TABLES_FIELDS}#";
	String FORM_FOREIGN_TABLES_INDEX_MODAL = "#{FORM_FOREIGN_TABLES_INDEX_MODAL}#";


	//OVDJE POCINJE STARO

	String IMPORT_FOREIGN_KEYS_TABLE_NAME = "#{IMPORT_FOREIGN_KEYS_TABLE_NAME}#";
	String IMPORT_FOREIGN_KEYS_TABLE_NAME_IN_SERVICE = "#{IMPORT_FOREIGN_KEYS_TABLE_NAME_IN_SERVICE}#";
	String IMPORT_TABLE_SERVICE_FOREIGN_KEYS = "#{IMPORT_TABLE_SERVICE_FOREIGN_KEYS}#";
	String MAP_COLUMNS_IN_TYPE_FIELDS = "#{MAP_COLUMNS_IN_TYPE_FIELDS}#";
	String HEADER_OF_INDEX_TABLE = "#{HEADER_OF_INDEX_TABLE}#";
	String DEFAULT_VALUES_OF_COLUMNS = "#{DEFAULT_VALUES_OF_COLUMNS}#";
	String NESTED_CATCH_FOREIGN_OBJECTS = "#{NESTED_CATCH_FOREIGN_OBJECTS}#";
	String INPUT_FIELDS_OF_TABLE = "#{INPUT_FIELDS_OF_TABLE}#";
	String TABLE_OBJECT_DETAILS_NO_FOREIGN_KEY = "#{TABLE_OBJECT_DETAILS_NO_FOREIGN_KEY}#";
	String TABLE_OBJECT_DETAILS_FOREIGN_KEY = "#{TABLE_OBJECT_DETAILS_FOREIGN_KEY}#";
	String TABLES_WHICH_REFERENCE_THIS_TABLE = "#{TABLES_WHICH_REFERENCE_THIS_TABLE}#";
	String TABLE_COLUMNS_IN_ROW = "#{TABLE_COLUMNS_IN_ROW}#";
	String IMPORT_INDEX_TABLE_WHICH_REFERENCE_THIS_TABLE = "#{IMPORT_INDEX_TABLE_WHICH_REFERENCE_THIS_TABLE}#";
	String FORM_OF_FOREIGN_TABLES = "#{FORM_OF_FOREIGN_TABLES}#";
	String IMPORT_FORM_OF_FOREIGN_TABLES = "#{IMPORT_FORM_OF_FOREIGN_TABLES}#";
	String ON_SAVE_FOREIGN_OBJECT = "#{ON_SAVE_FOREIGN_OBJECT}#";
	String ON_CHANGE_FIELD_FOREIGN_OBJECT = "#{ON_CHANGE_FIELD_FOREIGN_OBJECT}#";
	String GUARDED_ROUTES_OF_TABLES="#{GUARDED_ROUTES_OF_TABLES}#";
	String IMPORT_COMPONENTS_OF_TABLES="#{IMPORT_COMPONENTS_OF_TABLES}#";
	String TABLE_FILTER_OPTIONS="#{TABLE_FILTER_OPTIONS}#";
	String IMPORT_PAGE_OF_FOREIGN_TABLES="#{IMPORT_PAGE_OF_FOREIGN_TABLES}#";
	String IMPORT_INDEX_TABLE_WHICH_REFECENCE_THIS_TABLE="#{IMPORT_INDEX_TABLE_WHICH_REFECENCE_THIS_TABLE}#";

	String FUL_TABLE_NAME = "#{FUL_TABLE_NAME}#";
	String FLL_TABLE_NAME = "#{FLL_TABLE_NAME}#";
	String TABLE_SERVICE = "#{TABLE_SERVICE}#";
	String INDEX_TABLE_NAME = "#{INDEX_TABLE_NAME}#";
	String AUL_TABLE_NAME = "#{AUL_TABLE_NAME}#";
	String DEFAULT_TABLE_OBJECT = "#{DEFAULT_TABLE_OBJECT}#";
	String ASL_TABLE_NAME = "#{ASL_TABLE_NAME}#";
	String TABLE_FORM = "#{TABLE_FORM}#";
	String CREATE_TABLE_NAME = "#{CREATE_TABLE_NAME}#";
	String EDIT_TABLE_NAME = "#{EDIT_TABLE_NAME}#";
	String PAGE_TABLE_NAME = "#{PAGE_TABLE_NAME}#";
	String TABLE_EDIT_LINK = "#{TABLE_EDIT_LINK}#";
	String TABLE_PRIMARY_KEY_COLUMN = "#{TABLE_PRIMARY_KEY_COLUMN}#";
	String TABLES_ARRAY= "#{TABLES_ARRAY}#";
}
