package com.master.codegenerator.reactGenerator;

public interface ReactGeneratorConstant {

    String SYSTEM_API_ROUTES = "#{SYSTEM_API_ROUTES}#";
    String REACT_APPLICATION_ROUTES = "#{REACT_APPLICATION_ROUTES}#";
    String APPLICATION_SIDEBAR_ITEMS = "#{APPLICATION_SIDEBAR_ITEMS}#";
    String APPLICATION_PRIVATE_ROUTER_IMPORT = "#{APPLICATION_PRIVATE_ROUTER_IMPORT}#";
    String APPLICATION_PRIVATE_ROUTER_PATH = "#{APPLICATION_PRIVATE_ROUTER_PATH}#";

    String IMPORT_FOREIGN_TABLE_TYPES = "#{IMPORT_FOREIGN_TABLE_TYPES}#";

    String TABLE_ENUM_TYPES = "#{TABLE_ENUM_TYPES}#";

    String TABLE_COLUMNS_CONFIGURATION = "#{TABLE_COLUMNS_CONFIGURATION}#";
    String TABLE_PRIMARY_KEY_COLUMN_TYPE = "#{TABLE_PRIMARY_KEY_COLUMN_TYPE}#";

    String INDEX_OF_TABLES_WHICH_REFERENCE_THIS_TABLE = "#{INDEX_OF_TABLES_WHICH_REFERENCE_THIS_TABLE}#";
    String PAGE_OF_FOREIGN_TABLES = "#{PAGE_OF_FOREIGN_TABLES}#";
    String IMPORT_FOREIGN_TABLE_TYPES_IN_COMPONENT = "#{IMPORT_FOREIGN_TABLE_TYPES_IN_COMPONENT}#";
    String IMPORT_INDEX_OF_FOREIGN_TABLES = "#{IMPORT_INDEX_OF_FOREIGN_TABLES}#";

    String STATE_FOR_MODAL_OF_FOREIGN_TABLES = "#{STATE_FOR_MODAL_OF_FOREIGN_TABLES}#";
    String WATCH_TABLE_FOREIGN_OBJECTS = "#{WATCH_TABLE_FOREIGN_OBJECTS}#";

    String FORM_CHECK_FOREIGN_FIELDS = "#{FORM_CHECK_FOREIGN_FIELDS}#";

    String FORM_FOREIGN_TABLES_FIELDS = "#{FORM_FOREIGN_TABLES_FIELDS}#";
    String FORM_FOREIGN_TABLES_INDEX_MODAL = "#{FORM_FOREIGN_TABLES_INDEX_MODAL}#";
    String MAP_COLUMNS_IN_TYPE_FIELDS = "#{MAP_COLUMNS_IN_TYPE_FIELDS}#";

    String TABLE_OBJECT_DETAILS_NO_FOREIGN_KEY = "#{TABLE_OBJECT_DETAILS_NO_FOREIGN_KEY}#";

    String IMPORT_INDEX_TABLE_WHICH_REFERENCE_THIS_TABLE = "#{IMPORT_INDEX_TABLE_WHICH_REFERENCE_THIS_TABLE}#";

    String IMPORT_PAGE_OF_FOREIGN_TABLES = "#{IMPORT_PAGE_OF_FOREIGN_TABLES}#";


    String FUL_TABLE_NAME = "#{FUL_TABLE_NAME}#";
    String FLL_TABLE_NAME = "#{FLL_TABLE_NAME}#";


    String AUL_TABLE_NAME = "#{AUL_TABLE_NAME}#";

    String TABLE_PRIMARY_KEY_COLUMN = "#{TABLE_PRIMARY_KEY_COLUMN}#";

}
