package com.schema.api.auth.models;

public enum PermissionEnum {
KORISNICI_READ,
KORISNICI_CREATE,
KORISNICI_UPDATE,
KORISNICI_DELETE,
PROIZVODI_READ,
PROIZVODI_CREATE,
PROIZVODI_UPDATE,
PROIZVODI_DELETE,
NARUDZBE_READ,
NARUDZBE_CREATE,
NARUDZBE_UPDATE,
NARUDZBE_DELETE,
}
